version: '3.8'

services:
  api:
    build:
      context: ./src
      dockerfile: Monkify.Api/Dockerfile
    ports:
      - "6001:6001"
    environment:
      - ASPNETCORE_URLS=http://+:6001
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Monkify=Server=database;Database=Monkify;User Id=sa;Password=Monkify@123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - database
      - consumers
    networks:
      - monkify-network

  consumers:
    build:
      context: ./src
      dockerfile: Monkify.Consumers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Monkify=Server=database;Database=Monkify;User Id=sa;Password=Monkify@123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - database
    networks:
      - monkify-network

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Monkify@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - monkify-network

networks:
  monkify-network:
    driver: bridge