version: '3.8'

services:
  api:
    build:
      context: ./src
      dockerfile: Monkify.Api/Dockerfile
    ports:
      - "6001:6001"
    environment:
      - ASPNETCORE_URLS=http://+:6001
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Monkify=Server=database;Database=Monkify;User Id=sa;Password=Monkify@123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - database
      - consumers
    networks:
      - monkify-network

  consumers:
    build:
      context: ./src
      dockerfile: Monkify.Consumers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Monkify=Server=database;Database=Monkify;User Id=sa;Password=Monkify@123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - database
    networks:
      - monkify-network

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Monkify@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - monkify-network
      
  # ───────────────────────────── Zookeeper ────────────────────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - monkify-network

  # ───────────────────────────── Kafka Broker ─────────────────────────
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    networks:
      - monkify-network

networks:
  monkify-network:
    driver: bridge