version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Monkify@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  monkify.api:
    build: .
    depends_on:
      - sqlserver
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Monkify: "Server=sqlserver,1433;Database=Monkify;User Id=sa;Password=Monkify@123;TrustServerCertificate=True;Encrypt=False;"
      ConnectionStrings__Logs: "Server=sqlserver,1433;Database=Logs;User Id=sa;Password=Monkify@123;TrustServerCertificate=True;Encrypt=False;"