//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monkify.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monkify.Common.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If you requested a transaction and it has a different amount than you desired. You can request a refund for the transaction sending an email with the signature to marcusruas.andrade@gmail.com.
        /// </summary>
        public static string AdviceOnDifferentSignatureBetAmount {
            get {
                return ResourceManager.GetString("AdviceOnDifferentSignatureBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bet is not in the status to receive refund..
        /// </summary>
        public static string BetCannotReceiveRefund {
            get {
                return ResourceManager.GetString("BetCannotReceiveRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bet has not won, therefore cannot receive a reward for this session..
        /// </summary>
        public static string BetCannotReceiveReward {
            get {
                return ResourceManager.GetString("BetCannotReceiveReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bet has already been refunded..
        /// </summary>
        public static string BetHasAlreadyBeenRefunded {
            get {
                return ResourceManager.GetString("BetHasAlreadyBeenRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bet has already been rewarded..
        /// </summary>
        public static string BetHasAlreadyBeenRewarded {
            get {
                return ResourceManager.GetString("BetHasAlreadyBeenRewarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bet reward cannot be bigger than the pot..
        /// </summary>
        public static string BetRewardBiggerThanThePot {
            get {
                return ResourceManager.GetString("BetRewardBiggerThanThePot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The system could not register this bet at the moment, please try again later..
        /// </summary>
        public static string FailedToRegisterBet {
            get {
                return ResourceManager.GetString("FailedToRegisterBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested payment signature is not valid. Please check the data and try again..
        /// </summary>
        public static string InvalidPaymentSignature {
            get {
                return ResourceManager.GetString("InvalidPaymentSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested payment signature has already been used. Make another transaction with the appropriate amount..
        /// </summary>
        public static string PaymentSignatureHasBeenUsed {
            get {
                return ResourceManager.GetString("PaymentSignatureHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested session was not found or is not receiving bets at the current moment..
        /// </summary>
        public static string SessionNotValidForBets {
            get {
                return ResourceManager.GetString("SessionNotValidForBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Session has no bets..
        /// </summary>
        public static string SessionWithNoBets {
            get {
                return ResourceManager.GetString("SessionWithNoBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are no winners in this session. Transfers cannot be made..
        /// </summary>
        public static string SessionWithoutWinners {
            get {
                return ResourceManager.GetString("SessionWithoutWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested payment signature has sent less tokens than informed in the request. .
        /// </summary>
        public static string SignaturePaidLessThanBetAmount {
            get {
                return ResourceManager.GetString("SignaturePaidLessThanBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested payment signature has sent more tokens than informed in the request. .
        /// </summary>
        public static string SignaturePaidMoreThanBetAmount {
            get {
                return ResourceManager.GetString("SignaturePaidMoreThanBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested payment signature have not sent tokens from the request wallet. Please try sending a valid transaction..
        /// </summary>
        public static string SignatureWithoutBetAccount {
            get {
                return ResourceManager.GetString("SignatureWithoutBetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The requested payment signature have not sent tokens to our accounts. Please try sending a valid transaction..
        /// </summary>
        public static string SignatureWithoutOwnerAccount {
            get {
                return ResourceManager.GetString("SignatureWithoutOwnerAccount", resourceCulture);
            }
        }
    }
}
